version: 0.0.{build}

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\talker


branches:
  only:
    - master


environment:
  GOPATH: c:\gopath
  matrix:
    - GO: "c:\\go\\bin"
      - GOVERSION: 15.5
    - GO: "C:\\go114\\bin"
      - GOVERSION: 1.14
    - GO: "C:\\go113\\bin"
      - GOVERSION: 1.13
    - GO: "C:\\go112\\bin"
      - GOVERSION: 1.12

init:
  - go version


install:
  - curl -LJO "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r3.7z" -o c:\mingw-w64.7z
  - 7z x -oC:\mymingw64 winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r3.7z
  - set PATH=C:\mymingw64\mingw64\bin;%PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;%GO%;%PATH%
  - go env

build_script:
  - go test .
  - cmd: cd examples
  - cmd: copy ..\lib\x64\*.dll .
  - go build onlysapi.go && onlysapi.exe
  - go build getscreenreadername.go && getscreenreadername.exe
  - go build example1.go && example1.exe
  - go build example2.go && example2.exe

