version: 0.0.{build}

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\talker


branches:
  only:
    - master


environment:
  GOPATH: C:\gopath
  matrix:
    - GO: "c:\\go"
      GOVERSION: 15.5
    - GO: "C:\\go114"
      GOVERSION: 1.14
    - GO: "C:\\go113"
      GOVERSION: 1.13


init:
  - "%GO%\\bin\\go.exe version"


install:
  - curl -LJO -o "C:\mingw-w64.7z" "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-8.0.0-r7/winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r7.7z"
  - 7z x -oC:\mymingw64 winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r7.7z
  - set PATH=C:\mymingw64\mingw64\bin;%PATH%
  - set GOROOT=%GO%
  - set GOTOOLDIR=%GO%\pkg\tool\windows_amd64
  - "%GO%\\bin\\go.exe env"

build_script:
  - "%GO%\\bin\\go.exe test ."
  - cmd: cd examples
  - cmd: copy ..\lib\x64\*.dll .
  - "%GO%\\bin\\go.exe build onlysapi.go && onlysapi.exe"
  - "%GO%\\bin\\go.exe build getscreenreadername.go && getscreenreadername.exe"
  - "%GO%\\bin\\go.exe build example1.go && example1.exe"
  - "%GO%\\bin\\go.exe build example2.go && example2.exe"

