version: 0.0.{build}

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\talker

branches:
  only:
    - master

environment:
  GOPATH: C:\gopath
  matrix:
    - GO: "c:\\go"
    - GO: "C:\\go116"
    - GO: "C:\\go115"
    - GO: "C:\\go114"
    - GO: "C:\\go113"

init:
  - "%GO%\\bin\\go.exe version"

install:
  - set GOROOT=%GO%
  - set GOTOOLDIR=%GO%\pkg\tool\windows_amd64
  - "%GO%\\bin\\go.exe env"

build_script:
  - "%GO%\\bin\\go.exe vet ."
  - "%GO%\\bin\\go.exe build ."
  - cmd: cd examples
  - cmd: copy ..\lib\x64\*.dll .
  - "%GO%\\bin\\go.exe build onlysapi.go && onlysapi.exe"
  - "%GO%\\bin\\go.exe build getscreenreadername.go && getscreenreadername.exe"
  - "%GO%\\bin\\go.exe build example1.go && example1.exe"
  - "%GO%\\bin\\go.exe build example2.go && example2.exe"

