version: 0.0.{build}

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\talker

branches:
  only:
    - master


environment:
  GOPATH: c:\gopath

init:
  - go version

install:
  - curl "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r3.7z" -o C:\mingw64
  - 7z x -oC:\mymingw64 C:\mingw64
  set PATH=C:\mymingw64\bin;%PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go env

build_script:
  - go test .
  - cmd: cd examples
  - go build onlysapi.go
  - go build getscreenreadername.go
  - go build example1.go
  - go build example2.go

