version: 0.0.{build}
image: MinGW-w64 8.1.0 x86_64

platform:
  - x64
  - x86

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\talker

environment:
  GOPATH: c:\gopath
    
init:
  - go version

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin;%PATH%
  - go version
  - go env


build_script:
  - go test .
  - cmd: cd examples
  - go build onlysapi.go
  - go build getscreenreadername.go
  - go build example1.go
  - go build example2.go

