version: 0.0.1.{build}

platform:
  - x64
  - x86

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\talker

environment:
  GOPATH: c:\gopath
  matrix:
    - CI_ARCH: i686
    - CI_ARCH: x86_64

install:
  - curl "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-%CI_ARCH%-posix-dwarf-gcc-10.2.0-mingw-w64-8.0.0-r3.7z" -o C:\mingw%CI_ARCH%
  - 7z x -oC:\mingw%CI_ARCH% winlibs-%CI_ARCH%-posix-dwarf-gcc-10.2.0-mingw-w64-8.0.0-r3.7z
  - set PATH=C:mingw%CI_ARCH%\bin;%PATH%
  
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env


build_script:
  - go test .
  - cmd: cd examples
  - go build onlysapi.go
  - go build getscreenreadername.go
  - go build example1.go
  - go build example2.go

